//
// Created by Igor Lapin on 31/08/2020.
//

#ifndef ANDROID_NDK_OPENGL_RESEARCH_ANDROIDMEDIAPLAYERMUSICPLAYER_H
#define ANDROID_NDK_OPENGL_RESEARCH_ANDROIDMEDIAPLAYERMUSICPLAYER_H


#include <engine_3d/MusicPlayer.h>

class AndroidMediaPlayerMusicPlayer {

};


#endif //ANDROID_NDK_OPENGL_RESEARCH_ANDROIDMEDIAPLAYERMUSICPLAYER_H
