//
// Created by Igor Lapin on 03/07/2020.
//

#ifndef ANDROID_NDK_OPENGL_RESEARCH_ANDROIDMESHRENDERERFACTORY_H
#define ANDROID_NDK_OPENGL_RESEARCH_ANDROIDMESHRENDERERFACTORY_H


class AndroidMeshRendererFactory {

};


#endif //ANDROID_NDK_OPENGL_RESEARCH_ANDROIDMESHRENDERERFACTORY_H
