//
// Created by Igor Lapin on 03/07/2020.
//

#ifndef ANDROID_NDK_OPENGL_RESEARCH_ASSIMPINDEX_H
#define ANDROID_NDK_OPENGL_RESEARCH_ASSIMPINDEX_H


class AssimpIndex {

};


#endif //ANDROID_NDK_OPENGL_RESEARCH_ASSIMPINDEX_H
